{% set version = "0.12.1" %}

package:
  name: json-c
  version: {{ version }}

source:
  fn: json-c-{{ version }}.tar.gz
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-{{ version }}.tar.gz
  sha256: 2a136451a7932d80b7d197b10441e26e39428d67b1443ec43bbba824705e1123

build:
  number: 2
  skip: True  # [win]
  run_exports:
    # remove symbols and may change SONAME.  Keep to minor version.
    - {{ pin_subpackage('json-c', max_pin='x.x') }}

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - libtool

test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [unix]
    - test -f ${PREFIX}/lib/libjson-c.so  # [linux]
    - test -f ${PREFIX}/lib/libjson-c.dylib  # [osx]
    - conda inspect linkages -p ${PREFIX} json-c  # [linux]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_file: COPYING
  summary: 'A JSON implementation in C.'

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
