{% set version = "0.16" %}

package:
  name: json-c
  version: {{ version }}

source:
  fn: json-c-{{ version }}.tar.gz
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-{{ version }}.tar.gz
  sha256: 8e45ac8f96ec7791eaf3bb7ee50e9c2100bbbc87b8d0f1d030c5ba8a0288d96b

build:
  number: 0
  run_exports:
    # remove symbols and may change SONAME.  Keep to minor version.
    - {{ pin_subpackage('json-c', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig           # [unix]
    - {{ compiler('c') }}
    - cmake >=2.8
    - ninja-base
test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [unix]
    - test -f ${PREFIX}/lib/libjson-c.so  # [linux]
    - test -f ${PREFIX}/lib/libjson-c.dylib  # [osx]
    - test -f ${PREFIX}/include/json-c/json.h  # [unix]
    - if not exist %LIBRARY_BIN%/json-c.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%/json-c.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%/json-c/json.h exit 1  # [win]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A JSON implementation in C.
  description: |
    A JSON implementation in C.
  dev_url: https://github.com/json-c/json-c
  doc_url: https://json-c.github.io/json-c/

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
