{% set name = "json-c" %}
{% set version = "0.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://s3.amazonaws.com/{{ name }}_releases/releases/{{ name }}-{{ version }}.tar.gz
  sha256: 876ab046479166b869afc6896d288183bbc0e5843f141200c677b3e8dfb11724

build:
  number: 0
  run_exports:
    # remove symbols and may change SONAME.  Keep to minor version.
    - {{ pin_subpackage('json-c', max_pin='x.x') }}
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - gnuconfig           # [unix]
    - {{ compiler('c') }}
    - cmake >=2.8
    - ninja-base
test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [unix]
    - test -f ${PREFIX}/lib/libjson-c.so  # [linux]
    - test -f ${PREFIX}/lib/libjson-c.dylib  # [osx]
    - test -f ${PREFIX}/include/json-c/json.h  # [unix]
    - if not exist %LIBRARY_BIN%/json-c.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%/json-c.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%/json-c/json.h exit 1  # [win]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A JSON implementation in C.
  description: |
    A JSON implementation in C.
  dev_url: https://github.com/json-c/json-c
  doc_url: https://json-c.github.io/json-c/

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
