travis:
  secure:
    BINSTAR_TOKEN: fREcpReb8/teZkKLHhP0Y3Lrsc1sAb4heNS4WloWyyBJ+cDelFxF3W8SCtLzso/MhDIonBjAOjfD3mj+YkqbPoFWA96MxuD/oT1A81OqSlp6PAPEG27ro0T7tdKtr9vV0Yfq+sgxo+IVR/QYqm/6pTtj8pkP1B4nulXLAOXk6Qokb7fNEetIckY8ulZlSuZg5A0aoV2+YWOfPGmKAQ4aEpyoDWWcoceFLjyIQ4tD7HILd5yFIKun/psnKuKS8XUAxH7HUWR58Ls1bdSmMY5MLg0EYqeo0sbPaumEcDHgVvK6i0RX/dVOydhQ3O/vQhpVNz7SelAf033UyhMdZutE/IxZuMmKLzlhBuXXGCG3bV7hzWtvxLkigbbIjcogQAFqPRP4KrCiLCtIw4WdZC4soaxSv9sfhFYgTj+YtdrATDhj+6mTXgSaYuE6ryKoz1jpNaABoarpUt0H0DqN9V4MigmpCeJBmWc2KNbNe7tjOmv9x6XMp/5XfgAhpjyA2q5Vjph/2xbX01gOPzLVsEF7l1lexDdHxgClWBfrwvHm+z+YVBVKM3OcxVxzkjtYGoDhDQaKG1WYQKTMxFV5WuFkGcAxSP4QoM58Rc5fXFMI5Ogo5HsZaWClEEQWJasKrH2GOwuKPWrBZD66MwZYcA5RkvgAR7akOeXyRNmyp453dg8=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
