travis:
  secure:
    BINSTAR_TOKEN: mi3SdPFd2ek5YY9RcVgL7msKEfzF4841pD73EhaM75mDnJp+mIxt6UkfaBzjg8W47hDXJsta1Vw+/c0Rp4LfyxEJp/JLW8tRtVGjD2WJ0kRqPzBkG+N7u27y70OlTARavQQQ/NkrfCS9xeZqbBsrw2rf+vfGi4jHnPxiurBSoTrk8SJt0fOjaB/z8D6La3hPqzdRXiuha6Pp2UuNn6UqfbCuTsaM1PEhqrFK5nEZ1bUx6taZ3QBaaI0Bg2DTzOhh5JVtXKpyUklxLB2VCSDOzYhDDbme/j+aEcWIe6X+Fsl0sW987qv1zZjdfpS++uHe+KmMW3yydP+tF9+pSDEfidFSBncVhkt7yFiIMgoKDygUG5ptz2/PF6q5fYN3FE7Gp6M/CXvwGUUV/HQ8vCj16gn7+NswQzATwfWniMvgXjp+hwQwHfiVbO+yNpHKKu85Ln2Efq9dD+geU6bk4YYXr1SWg7cihqYYmWrzaAtf6mFVpW+6Jau7yy2LQtzFH8Oc8eXjq8vq6NW1DUVAAyObRymIYgLEbJq303PkUjXHM5bnwN06NjiOg1D1splHTq5Jh1pbluMEan9xcOEMmihyoIacBR5uKPJtbQz2KGNtEKuwuMB7r/DtOpOQbKo6Hao/SIrPsY5ozY6aEOdO4MS01I7qSpzTjWe+78YXwRoYfxk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
